version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: ordering-system-db
      DB_PORT: 5432
      EMAIL_PASSWORD: eaqbzonjkzhbhrxl
      EMAIL_USER: TESTEMAIL@gmail.com
      EMAIL_SERVICE: gmail
      EMAIL_HOST: smtp.gmail.com
      EMAIL_RECIEVER : test@gmail.com
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordering-system-db
    volumes:
      - ./docker-entrypoint-initdb.d/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./docker-entrypoint-initdb.d/02_insert_data.sql:/docker-entrypoint-initdb.d/02_insert_data.sql