openapi: 3.0.3
info:
  title: Ordering System
  version: 1.0.0
  description: This is an ordering system based on OAS 3.0.0
servers:
  - url: http://localhost:3000/
paths:
  /api/order:
    post:
      summary: Place an order
      description: Endpoint to place an order for products
      operationId: placeOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                        description: ID of the product to order
                      quantity:
                        type: integer
                        description: Quantity of the product to order
            example:
              products:
                - product_id: 1
                  quantity: 2
                - product_id: 2
                  quantity: 1
      responses:
        '201':
          description: Order added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A success message
                  order:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the order
                      order_items:
                        type: array
                        items:
                          type: object
                          properties:
                            product_id:
                              type: integer
                              description: The ID of the product
                            quantity:
                              type: string
                              description: The quantity of the product
              example:
                message: Order added successfully
                order:
                  id: 129
                  order_items:
                    - product_id: 1
                      quantity: "2"
                    - product_id: 1
                      quantity: "2"
        '400':
          description: Bad request to server
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                invalid-product:
                  value:
                    error: Invalid product in request payload
                missing-products:
                  value:
                    error: Invalid request products array is missing
        '500':
          description: server error
          content:
            application/json:
              examples:
                server-error:
                  value: '{"message": "Internal server error"}'
        '404':
          description: Ingredients not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                no-ingredients:
                  value:
                    error: Ingredients not available to fulfill order
      tags:
        - Orders
